server:
  port: 8080
  servlet:
    context-path: /app
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    password: wpay-2022
    url: jdbc:postgresql://localhost:5432/Prueba
    username: wpay
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: create
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          charset_name: UTF-8
  #          import_files: scripts/1_document_type.sql, scripts/user.sql, scripts/4_modules.sql, scripts/5_permissions.sql, scripts/6_roles.sql, scripts/7_email_template.sql, scripts/types.sql , scripts/test_data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
              client-secret: ${google.client-secret}

  #              github:
  #                client-id: your github client-id
  #                client-secret: your github client-secret
settings:
  url:
    front: http://localhost:4200/
  application:
    name: SpringSecurity
  social-networks:
  auth:
    token-time: 30
  encryption:
    aes:

